const labels = {
  'app.title':           { tcg: 'TCG Price Tracker',        stealth: 'Sistema de Dados' },
  'app.brand':           { tcg: 'TCG Tracker',              stealth: 'Analytics' },

  'nav.dashboard':       { tcg: 'Dashboard',                stealth: 'Painel' },
  'nav.import':          { tcg: 'Importar PDF',             stealth: 'Carregar Dados' },
  'nav.collection':      { tcg: 'Minha Coleção',            stealth: 'Base de Registros' },
  'nav.history':         { tcg: 'Histórico',                stealth: 'Log de Operações' },

  'footer.imports':      { tcg: 'importações',             stealth: 'operações' },
  'footer.cards':        { tcg: 'cartas',                   stealth: 'registros' },

  'dashboard.heading':         { tcg: 'Dashboard',               stealth: 'Painel' },
  'dashboard.lastUpdate':      { tcg: 'Última atualização:',     stealth: 'Última atualização:' },
  'dashboard.collectionValue': { tcg: 'Valor da Coleção',        stealth: 'Valor Total' },
  'dashboard.cards':           { tcg: 'Cartas',                  stealth: 'Registros' },
  'dashboard.units':           { tcg: 'Unidades',                stealth: 'Unidades' },
  'dashboard.variation':       { tcg: 'Variação',                stealth: 'Delta' },
  'dashboard.emptyTitle':      { tcg: 'Nenhuma coleção importada',       stealth: 'Nenhuma base carregada' },
  'dashboard.emptyMsg':        { tcg: 'Importe seu primeiro PDF para começar a acompanhar a evolução dos preços.', stealth: 'Carregue seu primeiro arquivo para acompanhar a evolução dos valores.' },
  'dashboard.emptyBtn':        { tcg: 'Importar primeiro PDF',           stealth: 'Carregar primeiro arquivo' },
  'dashboard.singleTitle':     { tcg: 'Apenas uma importação',           stealth: 'Apenas uma carga' },
  'dashboard.singleMsg':       { tcg: 'Importe um novo PDF em outra data para começar a comparar os preços.', stealth: 'Carregue um novo arquivo em outra data para começar a comparar os valores.' },
  'dashboard.singleBtn':       { tcg: 'Importar novo PDF',              stealth: 'Carregar novo arquivo' },
  'dashboard.topGainers':      { tcg: 'Top 5 — Maiores Altas',          stealth: 'Top 5 — Crescimento' },
  'dashboard.topLosers':       { tcg: 'Top 5 — Maiores Quedas',         stealth: 'Top 5 — Redução' },
  'dashboard.evolution':       { tcg: 'Evolução da Coleção',            stealth: 'Evolução da Base' },
  'dashboard.chartLabel':      { tcg: 'Valor Total (Compra Menor)',     stealth: 'Valor Total (Entrada Mín)' },
  'dashboard.changes':         { tcg: 'Alterações na Coleção',          stealth: 'Alterações na Base' },
  'dashboard.newCards':        { tcg: 'Novas cartas',                   stealth: 'Novos registros' },
  'dashboard.removedCards':    { tcg: 'Cartas removidas',               stealth: 'Registros removidos' },

  'table.card':           { tcg: 'Carta',               stealth: 'Registro' },
  'table.edition':        { tcg: 'Edição',              stealth: 'Categoria' },
  'table.number':         { tcg: 'Nº',                  stealth: 'Ref' },
  'table.numberFull':     { tcg: 'Número',              stealth: 'Referência' },
  'table.name':           { tcg: 'Nome',                stealth: 'Nome' },
  'table.nameCol':        { tcg: 'Nome ↕',              stealth: 'Nome ↕' },
  'table.editionCol':     { tcg: 'Edição ↕',            stealth: 'Categoria ↕' },
  'table.qtd':            { tcg: 'Qtd',                 stealth: 'Qtd' },
  'table.extra':          { tcg: 'Extra',               stealth: 'Obs' },
  'table.rarity':         { tcg: 'Raridade',            stealth: 'Nível' },
  'table.language':       { tcg: 'Idioma',              stealth: 'Idioma' },
  'table.condition':      { tcg: 'Cond.',               stealth: 'Estado' },
  'table.status':         { tcg: 'Status',              stealth: 'Status' },
  'table.previous':       { tcg: 'Anterior',            stealth: 'Anterior' },
  'table.current':        { tcg: 'Atual',               stealth: 'Atual' },
  'table.variation':      { tcg: 'Variação',            stealth: 'Delta' },
  'table.prevPrice':      { tcg: 'Preço Anterior ↕',    stealth: 'Valor Anterior ↕' },
  'table.currPrice':      { tcg: 'Preço Atual ↕',       stealth: 'Valor Atual ↕' },
  'table.diffR':          { tcg: 'Dif. (R$) ↕',         stealth: 'Dif. (R$) ↕' },
  'table.diffPercent':    { tcg: 'Dif. (%) ↕',          stealth: 'Dif. (%) ↕' },

  'table.import.date':    { tcg: 'Data Ref.',           stealth: 'Data Ref.' },
  'table.import.file':    { tcg: 'Arquivo',             stealth: 'Arquivo' },
  'table.import.cards':   { tcg: 'Cartas',              stealth: 'Registros' },
  'table.import.total':   { tcg: 'Valor Total',         stealth: 'Valor Total' },
  'table.import.variation': { tcg: 'Variação',          stealth: 'Delta' },
  'table.import.imported':  { tcg: 'Importado em',      stealth: 'Processado em' },

  'table.history.date':   { tcg: 'Data',                stealth: 'Data' },
  'table.history.qtd':    { tcg: 'Qtd',                 stealth: 'Qtd' },

  'price.buyMin':         { tcg: 'Compra Menor',        stealth: 'Entrada Mín' },
  'price.buyAvg':         { tcg: 'Compra Média',        stealth: 'Entrada Média' },
  'price.buyMax':         { tcg: 'Compra Maior',        stealth: 'Entrada Máx' },
  'price.sellMin':        { tcg: 'Venda Menor',         stealth: 'Saída Mín' },
  'price.sellAvg':        { tcg: 'Venda Média',         stealth: 'Saída Média' },
  'price.sellMax':        { tcg: 'Venda Maior',         stealth: 'Saída Máx' },

  'price.abbr.buyMin':    { tcg: 'C-Menor',             stealth: 'E-Mín' },
  'price.abbr.buyAvg':    { tcg: 'C-Médio',             stealth: 'E-Méd' },
  'price.abbr.buyMax':    { tcg: 'C-Maior',             stealth: 'E-Máx' },
  'price.abbr.sellMin':   { tcg: 'V-Menor',             stealth: 'S-Mín' },
  'price.abbr.sellAvg':   { tcg: 'V-Médio',             stealth: 'S-Méd' },
  'price.abbr.sellMax':   { tcg: 'V-Maior',             stealth: 'S-Máx' },

  'price.current':               { tcg: 'Preço Atual',                stealth: 'Valor Atual' },
  'price.minRegistered':         { tcg: 'Menor Registrado',           stealth: 'Mínimo Registrado' },
  'price.maxRegistered':         { tcg: 'Maior Registrado',           stealth: 'Máximo Registrado' },
  'price.displayLabel':          { tcg: 'Preço exibido:',             stealth: 'Valor exibido:' },

  'import.heading':         { tcg: 'Importar PDF',              stealth: 'Carregar Dados' },
  'import.subheading':      { tcg: 'Faça upload do PDF da coleção para extrair os preços das cartas.', stealth: 'Faça upload do arquivo para extrair os valores dos registros.' },
  'import.fileLabel':       { tcg: 'Arquivo PDF',              stealth: 'Arquivo' },
  'import.dateLabel':       { tcg: 'Data de referência',       stealth: 'Data de referência' },
  'import.processing':      { tcg: 'Processando...',           stealth: 'Processando...' },
  'import.processBtn':      { tcg: 'Processar PDF',            stealth: 'Processar Arquivo' },
  'import.reviewTitle':     { tcg: 'Conferência dos dados',    stealth: 'Conferência dos dados' },
  'import.cancelBtn':       { tcg: 'Cancelar',                 stealth: 'Cancelar' },
  'import.confirmBtn':      { tcg: 'Confirmar importação',     stealth: 'Confirmar carga' },
  'import.foundCards':      { tcg: 'Cartas encontradas',       stealth: 'Registros encontrados' },
  'import.units':           { tcg: 'Unidades',                 stealth: 'Unidades' },
  'import.errors':          { tcg: 'Erros',                    stealth: 'Erros' },
  'import.totalBuyMin':     { tcg: 'Total Compra Menor',       stealth: 'Total Entrada Mín' },
  'import.totalSellAvg':    { tcg: 'Total Venda Médio',        stealth: 'Total Saída Média' },
  'import.warningPrefix':   { tcg: 'linha(s) com possíveis problemas. Corrija-as antes de confirmar.', stealth: 'linha(s) com possíveis problemas. Corrija-as antes de confirmar.' },
  'import.addCard':         { tcg: '+ Adicionar carta',        stealth: '+ Adicionar registro' },
  'import.success':         { tcg: 'Importação realizada com sucesso!', stealth: 'Carga realizada com sucesso!' },
  'import.successMsg':      { tcg: 'cartas importadas para',   stealth: 'registros carregados para' },
  'import.duplicateTitle':  { tcg: 'Data já importada',        stealth: 'Data já carregada' },
  'import.duplicateMsg':    { tcg: 'Já existe uma importação para esta data. Deseja substituir os dados existentes?', stealth: 'Já existe uma carga para esta data. Deseja substituir os dados existentes?' },
  'import.replaceBtn':      { tcg: 'Substituir',               stealth: 'Substituir' },

  'collection.heading':           { tcg: 'Minha Coleção',           stealth: 'Base de Registros' },
  'collection.subheading':        { tcg: 'cartas exibidas',         stealth: 'registros exibidos' },
  'collection.searchLabel':       { tcg: 'Buscar',                  stealth: 'Buscar' },
  'collection.searchPlaceholder': { tcg: 'Nome da carta...',        stealth: 'Nome do registro...' },
  'collection.editionLabel':      { tcg: 'Edição',                  stealth: 'Categoria' },
  'collection.editionAll':        { tcg: 'Todas',                   stealth: 'Todas' },
  'collection.sortLabel':         { tcg: 'Ordenar',                 stealth: 'Ordenar' },
  'collection.sortName':          { tcg: 'Nome',                    stealth: 'Nome' },
  'collection.sortCurrPrice':     { tcg: 'Preço Atual',             stealth: 'Valor Atual' },
  'collection.sortPrevPrice':     { tcg: 'Preço Anterior',          stealth: 'Valor Anterior' },
  'collection.sortVarPercent':    { tcg: 'Maior Variação (%)',      stealth: 'Maior Delta (%)' },
  'collection.sortVarValue':      { tcg: 'Maior Variação (R$)',     stealth: 'Maior Delta (R$)' },
  'collection.sortRecent':        { tcg: 'Últimas Variações',       stealth: 'Últimos Deltas' },
  'collection.orderLabel':        { tcg: 'Ordem',                   stealth: 'Ordem' },
  'collection.orderDesc':         { tcg: 'Decrescente',             stealth: 'Decrescente' },
  'collection.orderAsc':          { tcg: 'Crescente',               stealth: 'Crescente' },
  'collection.emptyTitle':        { tcg: 'Nenhuma carta na coleção',     stealth: 'Nenhum registro na base' },
  'collection.emptyMsg':          { tcg: 'Importe um PDF para começar a acompanhar sua coleção.', stealth: 'Carregue um arquivo para começar a acompanhar sua base.' },
  'collection.emptyBtn':          { tcg: 'Importar PDF',            stealth: 'Carregar Dados' },
  'collection.prevBtn':           { tcg: 'Anterior',                stealth: 'Anterior' },
  'collection.nextBtn':           { tcg: 'Próximo',                 stealth: 'Próximo' },

  'history.heading':        { tcg: 'Histórico de Importações',    stealth: 'Log de Operações' },
  'history.subheading':     { tcg: 'importações realizadas',      stealth: 'operações realizadas' },
  'history.emptyTitle':     { tcg: 'Nenhuma importação',          stealth: 'Nenhuma operação' },
  'history.emptyMsg':       { tcg: 'Importe um PDF para ver o histórico aqui.', stealth: 'Carregue um arquivo para ver o log aqui.' },
  'history.emptyBtn':       { tcg: 'Importar PDF',                stealth: 'Carregar Dados' },
  'history.noVariation':    { tcg: '—',                           stealth: '—' },
  'history.deleteBtn':      { tcg: 'Excluir',                     stealth: 'Excluir' },
  'history.deleteTitle':    { tcg: 'Excluir importação',          stealth: 'Excluir operação' },
  'history.deleteMsg':      { tcg: 'Tem certeza que deseja excluir a importação de', stealth: 'Tem certeza que deseja excluir a operação de' },
  'history.deleteMsgSuffix': { tcg: '? Os preços associados também serão removidos.', stealth: '? Os valores associados também serão removidos.' },
  'history.deleteConfirm':  { tcg: 'Excluir',                     stealth: 'Excluir' },

  'modal.close':            { tcg: 'Fechar',                stealth: 'Fechar' },
  'modal.cancel':           { tcg: 'Cancelar',              stealth: 'Cancelar' },
  'modal.confirm':          { tcg: 'Confirmar',             stealth: 'Confirmar' },
  'modal.typeConfirm':      { tcg: 'Digite',                stealth: 'Digite' },
  'modal.typeConfirmEnd':   { tcg: 'para confirmar:',       stealth: 'para confirmar:' },
  'modal.totalsOk':         { tcg: 'Totais conferem',       stealth: 'Totais conferem' },
  'modal.totalsDiff':       { tcg: 'Divergência nos totais: R$', stealth: 'Divergência nos totais: R$' },

  'detail.cardFallback':    { tcg: 'Carta',                 stealth: 'Registro' },
  'detail.edition':         { tcg: 'Edição',                stealth: 'Categoria' },
  'detail.number':          { tcg: 'Número',                stealth: 'Referência' },
  'detail.rarity':          { tcg: 'Raridade',              stealth: 'Nível' },
  'detail.qtdLangCond':     { tcg: 'Qtd / Idioma / Cond.',  stealth: 'Qtd / Idioma / Estado' },
  'detail.priceCurrent':    { tcg: 'Preço Atual',           stealth: 'Valor Atual' },
  'detail.noHistory':       { tcg: 'Importe mais datas para visualizar a evolução.', stealth: 'Carregue mais datas para visualizar a evolução.' },
  'detail.historyTitle':    { tcg: 'Histórico',             stealth: 'Histórico' },
  'detail.ok':              { tcg: 'OK',                    stealth: 'OK' },
  'detail.errors':          { tcg: 'erro(s)',               stealth: 'erro(s)' },

  'error.noTable':          { tcg: 'Tabela de cartas nao encontrada no PDF',            stealth: 'Tabela de registros nao encontrada no arquivo' },
  'error.noCards':          { tcg: 'Nenhuma carta identificada no PDF. Verifique se o arquivo contém uma tabela de cartas.', stealth: 'Nenhum registro identificado no arquivo. Verifique se o arquivo contém uma tabela de registros.' },
  'error.process':          { tcg: 'Erro ao processar o PDF. O arquivo pode estar protegido ou corrompido.', stealth: 'Erro ao processar o arquivo. O arquivo pode estar protegido ou corrompido.' },
  'error.notPdf':           { tcg: 'O arquivo selecionado não é um PDF.',                stealth: 'O arquivo selecionado não é um arquivo válido.' },
  'error.saveFail':         { tcg: 'Erro ao salvar os dados no navegador.',              stealth: 'Erro ao salvar os dados no navegador.' },
  'error.backupInvalid':    { tcg: 'Arquivo de backup inválido',                         stealth: 'Arquivo de backup inválido' },
  'error.editionMissing':   { tcg: 'Edição ausente',          stealth: 'Categoria ausente' },
  'error.numberMissing':    { tcg: 'Número ausente',          stealth: 'Referência ausente' },
  'error.nameMissing':      { tcg: 'Nome ausente',            stealth: 'Nome ausente' },
  'error.unknown':          { tcg: 'Desconhecida',            stealth: 'Desconhecido' },
  'error.newCard':          { tcg: 'Nova carta',              stealth: 'Novo registro' },
  'error.edicaoAusente':    { tcg: 'Edicao ausente',          stealth: 'Categoria ausente' },
  'error.numeroAusente':    { tcg: 'Numero ausente',          stealth: 'Referencia ausente' },
  'error.nomeAusente':      { tcg: 'Nome ausente',            stealth: 'Nome ausente' },

  'data.normal':            { tcg: 'Normal',                  stealth: 'Normal' },
  'data.noCardsFound':      { tcg: 'Nenhuma carta encontrada',           stealth: 'Nenhum registro encontrado' },
  'data.noGainers':         { tcg: 'Nenhuma carta com valorização nesta comparação.', stealth: 'Nenhum registro com crescimento nesta comparação.' },
  'data.noLosers':          { tcg: 'Nenhuma carta com queda nesta comparação.',       stealth: 'Nenhum registro com redução nesta comparação.' },
}

export default labels
