const labels = {
  'app.title':           { tcg: 'TCG Price Tracker',        stealth: 'Sistema de Dados' },
  'app.brand':           { tcg: 'TCG Tracker',              stealth: 'Analytics' },

  'nav.dashboard':       { tcg: 'Dashboard',                stealth: 'Painel' },
  'nav.config':          { tcg: 'Configuracoes',            stealth: 'Configuracoes' },
  'nav.collection':      { tcg: 'Minha Colecao',            stealth: 'Base de Registros' },
  'nav.history':         { tcg: 'Historico',                stealth: 'Log de Operacoes' },

  'footer.imports':      { tcg: 'importacoes',             stealth: 'operacoes' },
  'footer.cards':        { tcg: 'cartas',                   stealth: 'registros' },

  'dashboard.heading':         { tcg: 'Dashboard',               stealth: 'Painel' },
  'dashboard.lastUpdate':      { tcg: 'Ultima atualizacao:',     stealth: 'Ultima atualizacao:' },
  'dashboard.collectionValue': { tcg: 'Valor da Colecao',        stealth: 'Valor Total' },
  'dashboard.cards':           { tcg: 'Cartas',                  stealth: 'Registros' },
  'dashboard.units':           { tcg: 'Unidades',                stealth: 'Unidades' },
  'dashboard.variation':       { tcg: 'Variacao',                stealth: 'Delta' },
  'dashboard.emptyTitle':      { tcg: 'Nenhuma colecao importada',       stealth: 'Nenhuma base carregada' },
  'dashboard.emptyMsg':        { tcg: 'Importe seu primeiro PDF para comecar a acompanhar a evolucao dos precos.', stealth: 'Carregue seu primeiro arquivo para acompanhar a evolucao dos valores.' },
  'dashboard.emptyBtn':        { tcg: 'Importar primeiro PDF',           stealth: 'Carregar primeiro arquivo' },
  'dashboard.singleTitle':     { tcg: 'Apenas uma importacao',           stealth: 'Apenas uma carga' },
  'dashboard.singleMsg':       { tcg: 'Importe um novo PDF em outra data para comecar a comparar os precos.', stealth: 'Carregue um novo arquivo em outra data para comecar a comparar os valores.' },
  'dashboard.singleBtn':       { tcg: 'Importar novo PDF',              stealth: 'Carregar novo arquivo' },
  'dashboard.topGainers':      { tcg: 'Top 5 - Maiores Altas',          stealth: 'Top 5 - Crescimento' },
  'dashboard.topLosers':       { tcg: 'Top 5 - Maiores Quedas',         stealth: 'Top 5 - Reducao' },
  'dashboard.evolution':       { tcg: 'Evolucao da Colecao',            stealth: 'Evolucao da Base' },
  'dashboard.chartLabel':      { tcg: 'Valor Total (Compra Menor)',     stealth: 'Valor Total (Entrada Min)' },
  'dashboard.changes':         { tcg: 'Alteracoes na Colecao',          stealth: 'Alteracoes na Base' },
  'dashboard.newCards':        { tcg: 'Novas cartas',                   stealth: 'Novos registros' },
  'dashboard.removedCards':    { tcg: 'Cartas removidas',               stealth: 'Registros removidos' },

  'table.card':           { tcg: 'Carta',               stealth: 'Registro' },
  'table.edition':        { tcg: 'Edicao',              stealth: 'Categoria' },
  'table.number':         { tcg: 'No',                  stealth: 'Ref' },
  'table.numberFull':     { tcg: 'Numero',              stealth: 'Referencia' },
  'table.name':           { tcg: 'Nome',                stealth: 'Nome' },
  'table.nameCol':        { tcg: 'Nome',                stealth: 'Nome' },
  'table.editionCol':     { tcg: 'Edicao',              stealth: 'Categoria' },
  'table.qtd':            { tcg: 'Qtd',                 stealth: 'Qtd' },
  'table.extra':          { tcg: 'Extra',               stealth: 'Obs' },
  'table.rarity':         { tcg: 'Raridade',            stealth: 'Nivel' },
  'table.language':       { tcg: 'Idioma',              stealth: 'Idioma' },
  'table.condition':      { tcg: 'Cond.',               stealth: 'Estado' },
  'table.status':         { tcg: 'Status',              stealth: 'Status' },
  'table.previous':       { tcg: 'Anterior',            stealth: 'Anterior' },
  'table.current':        { tcg: 'Atual',               stealth: 'Atual' },
  'table.variation':      { tcg: 'Variacao',            stealth: 'Delta' },
  'table.prevPrice':      { tcg: 'Preco Anterior',    stealth: 'Valor Anterior' },
  'table.currPrice':      { tcg: 'Preco Atual',       stealth: 'Valor Atual' },
  'table.diffR':          { tcg: 'Dif. (R$)',         stealth: 'Dif. (R$)' },
  'table.diffPercent':    { tcg: 'Dif. (%)',          stealth: 'Dif. (%)' },

  'table.import.date':    { tcg: 'Data Ref.',           stealth: 'Data Ref.' },
  'table.import.file':    { tcg: 'Arquivo',             stealth: 'Arquivo' },
  'table.import.cards':   { tcg: 'Cartas',              stealth: 'Registros' },
  'table.import.total':   { tcg: 'Valor Total',         stealth: 'Valor Total' },
  'table.import.variation': { tcg: 'Variacao',          stealth: 'Delta' },
  'table.import.imported':  { tcg: 'Importado em',      stealth: 'Processado em' },

  'table.history.date':   { tcg: 'Data',                stealth: 'Data' },
  'table.history.qtd':    { tcg: 'Qtd',                 stealth: 'Qtd' },

  'price.buyMin':         { tcg: 'Compra Menor',        stealth: 'Entrada Min' },
  'price.buyAvg':         { tcg: 'Compra Media',        stealth: 'Entrada Media' },
  'price.buyMax':         { tcg: 'Compra Maior',        stealth: 'Entrada Max' },
  'price.sellMin':        { tcg: 'Venda Menor',         stealth: 'Saida Min' },
  'price.sellAvg':        { tcg: 'Venda Media',         stealth: 'Saida Media' },
  'price.sellMax':        { tcg: 'Venda Maior',         stealth: 'Saida Max' },

  'price.abbr.buyMin':    { tcg: 'C-Menor',             stealth: 'E-Min' },
  'price.abbr.buyAvg':    { tcg: 'C-Medio',             stealth: 'E-Med' },
  'price.abbr.buyMax':    { tcg: 'C-Maior',             stealth: 'E-Max' },
  'price.abbr.sellMin':   { tcg: 'V-Menor',             stealth: 'S-Min' },
  'price.abbr.sellAvg':   { tcg: 'V-Medio',             stealth: 'S-Med' },
  'price.abbr.sellMax':   { tcg: 'V-Maior',             stealth: 'S-Max' },

  'price.current':               { tcg: 'Preco Atual',                stealth: 'Valor Atual' },
  'price.minRegistered':         { tcg: 'Menor Registrado',           stealth: 'Minimo Registrado' },
  'price.maxRegistered':         { tcg: 'Maior Registrado',           stealth: 'Maximo Registrado' },
  'price.displayLabel':          { tcg: 'Preco exibido:',             stealth: 'Valor exibido:' },

  'collection.heading':           { tcg: 'Minha Colecao',           stealth: 'Base de Registros' },
  'collection.subheading':        { tcg: 'cartas exibidas',         stealth: 'registros exibidos' },
  'collection.searchLabel':       { tcg: 'Buscar',                  stealth: 'Buscar' },
  'collection.searchPlaceholder': { tcg: 'Nome da carta...',        stealth: 'Nome do registro...' },
  'collection.editionLabel':      { tcg: 'Edicao',                  stealth: 'Categoria' },
  'collection.editionAll':        { tcg: 'Todas',                   stealth: 'Todas' },
  'collection.sortLabel':         { tcg: 'Ordenar',                 stealth: 'Ordenar' },
  'collection.sortName':          { tcg: 'Nome',                    stealth: 'Nome' },
  'collection.sortCurrPrice':     { tcg: 'Preco Atual',             stealth: 'Valor Atual' },
  'collection.sortPrevPrice':     { tcg: 'Preco Anterior',          stealth: 'Valor Anterior' },
  'collection.sortVarPercent':    { tcg: 'Maior Variacao (%)',      stealth: 'Maior Delta (%)' },
  'collection.sortVarValue':      { tcg: 'Maior Variacao (R$)',     stealth: 'Maior Delta (R$)' },
  'collection.sortRecent':        { tcg: 'Ultimas Variacoes',       stealth: 'Ultimos Deltas' },
  'collection.orderLabel':        { tcg: 'Ordem',                   stealth: 'Ordem' },
  'collection.orderDesc':         { tcg: 'Decrescente',             stealth: 'Decrescente' },
  'collection.orderAsc':          { tcg: 'Crescente',               stealth: 'Crescente' },
  'collection.emptyTitle':        { tcg: 'Nenhuma carta na colecao',     stealth: 'Nenhum registro na base' },
  'collection.emptyMsg':          { tcg: 'Importe um PDF para comecar a acompanhar sua colecao.', stealth: 'Carregue um arquivo para comecar a acompanhar sua base.' },
  'collection.emptyBtn':          { tcg: 'Importar PDF',            stealth: 'Carregar Dados' },
  'collection.prevBtn':           { tcg: 'Anterior',                stealth: 'Anterior' },
  'collection.nextBtn':           { tcg: 'Proximo',                 stealth: 'Proximo' },

  'history.heading':        { tcg: 'Historico de Importacoes',    stealth: 'Log de Operacoes' },
  'history.subheading':     { tcg: 'importacoes realizadas',      stealth: 'operacoes realizadas' },
  'history.emptyTitle':     { tcg: 'Nenhuma importacao',          stealth: 'Nenhuma operacao' },
  'history.emptyMsg':       { tcg: 'Importe um PDF para ver o historico aqui.', stealth: 'Carregue um arquivo para ver o log aqui.' },
  'history.emptyBtn':       { tcg: 'Importar PDF',                stealth: 'Carregar Dados' },
  'history.noVariation':    { tcg: '-',                           stealth: '-' },
  'history.deleteBtn':      { tcg: 'Excluir',                     stealth: 'Excluir' },
  'history.deleteTitle':    { tcg: 'Excluir importacao',          stealth: 'Excluir operacao' },
  'history.deleteMsg':      { tcg: 'Tem certeza que deseja excluir a importacao de', stealth: 'Tem certeza que deseja excluir a operacao de' },
  'history.deleteMsgSuffix': { tcg: '? Os precos associados tambem serao removidos.', stealth: '? Os valores associados tambem serao removidos.' },
  'history.deleteConfirm':  { tcg: 'Excluir',                     stealth: 'Excluir' },

  'modal.close':            { tcg: 'Fechar',                stealth: 'Fechar' },
  'modal.cancel':           { tcg: 'Cancelar',              stealth: 'Cancelar' },
  'modal.confirm':          { tcg: 'Confirmar',             stealth: 'Confirmar' },
  'modal.typeConfirm':      { tcg: 'Digite',                stealth: 'Digite' },
  'modal.typeConfirmEnd':   { tcg: 'para confirmar:',       stealth: 'para confirmar:' },
  'modal.totalsOk':         { tcg: 'Totais conferem',       stealth: 'Totais conferem' },
  'modal.totalsDiff':       { tcg: 'Divergencia nos totais: R$', stealth: 'Divergencia nos totais: R$' },

  'detail.cardFallback':    { tcg: 'Carta',                 stealth: 'Registro' },
  'detail.edition':         { tcg: 'Edicao',                stealth: 'Categoria' },
  'detail.number':          { tcg: 'Numero',                stealth: 'Referencia' },
  'detail.rarity':          { tcg: 'Raridade',              stealth: 'Nivel' },
  'detail.qtdLangCond':     { tcg: 'Qtd / Idioma / Cond.',  stealth: 'Qtd / Idioma / Estado' },
  'detail.priceCurrent':    { tcg: 'Preco Atual',           stealth: 'Valor Atual' },
  'detail.noHistory':       { tcg: 'Importe mais datas para visualizar a evolucao.', stealth: 'Carregue mais datas para visualizar a evolucao.' },
  'detail.historyTitle':    { tcg: 'Historico',             stealth: 'Historico' },
  'detail.ok':              { tcg: 'OK',                    stealth: 'OK' },
  'detail.errors':          { tcg: 'erro(s)',               stealth: 'erro(s)' },

  'error.noTable':          { tcg: 'Tabela de cartas nao encontrada no PDF',            stealth: 'Tabela de registros nao encontrada no arquivo' },
  'error.noCards':          { tcg: 'Nenhuma carta identificada no PDF. Verifique se o arquivo contem uma tabela de cartas.', stealth: 'Nenhum registro identificado no arquivo. Verifique se o arquivo contem uma tabela de registros.' },
  'error.process':          { tcg: 'Erro ao processar o PDF. O arquivo pode estar protegido ou corrompido.', stealth: 'Erro ao processar o arquivo. O arquivo pode estar protegido ou corrompido.' },
  'error.notPdf':           { tcg: 'O arquivo selecionado nao e um PDF.',                stealth: 'O arquivo selecionado nao e um arquivo valido.' },
  'error.saveFail':         { tcg: 'Erro ao salvar os dados no navegador.',              stealth: 'Erro ao salvar os dados no navegador.' },
  'error.backupInvalid':    { tcg: 'Arquivo de backup invalido',                         stealth: 'Arquivo de backup invalido' },
  'error.editionMissing':   { tcg: 'Edicao ausente',          stealth: 'Categoria ausente' },
  'error.numberMissing':    { tcg: 'Numero ausente',          stealth: 'Referencia ausente' },
  'error.nameMissing':      { tcg: 'Nome ausente',            stealth: 'Nome ausente' },
  'error.unknown':          { tcg: 'Desconhecida',            stealth: 'Desconhecido' },
  'error.newCard':          { tcg: 'Nova carta',              stealth: 'Novo registro' },
  'error.edicaoAusente':    { tcg: 'Edicao ausente',          stealth: 'Categoria ausente' },
  'error.numeroAusente':    { tcg: 'Numero ausente',          stealth: 'Referencia ausente' },
  'error.nomeAusente':      { tcg: 'Nome ausente',            stealth: 'Nome ausente' },

  'data.normal':            { tcg: 'Normal',                  stealth: 'Normal' },
  'data.noCardsFound':      { tcg: 'Nenhuma carta encontrada',           stealth: 'Nenhum registro encontrado' },
  'data.noGainers':         { tcg: 'Nenhuma carta com valorizacao nesta comparacao.', stealth: 'Nenhum registro com crescimento nesta comparacao.' },
  'data.noLosers':          { tcg: 'Nenhuma carta com queda nesta comparacao.',       stealth: 'Nenhum registro com reducao nesta comparacao.' },

  'config.heading':         { tcg: 'Configuracao',              stealth: 'Configuracao' },
  'config.subheading':      { tcg: 'Configure a URL da colecao para monitorar os precos automaticamente.', stealth: 'Configure a URL da fonte para monitorar os valores automaticamente.' },
  'config.urlLabel':        { tcg: 'URL da Colecao',            stealth: 'URL da Fonte' },
  'config.urlPlaceholder':  { tcg: 'https://www.ligapokemon.com.br/?view=colecao/colecao&id=...', stealth: 'https://...' },
  'config.intervalLabel':   { tcg: 'Intervalo',                 stealth: 'Intervalo' },
  'config.interval1m':     { tcg: '1 minuto',                  stealth: '1 minuto' },
  'config.interval5m':     { tcg: '5 minutos',                 stealth: '5 minutos' },
  'config.interval10m':    { tcg: '10 minutos',                stealth: '10 minutos' },
  'config.interval30m':    { tcg: '30 minutos',                stealth: '30 minutos' },
  'config.interval1h':     { tcg: '1 hora',                    stealth: '1 hora' },
  'config.saveBtn':         { tcg: 'Salvar e iniciar',          stealth: 'Salvar e iniciar' },
  'config.status':          { tcg: 'Status',                    stealth: 'Status' },
  'config.pause':           { tcg: 'Pausar',                    stealth: 'Pausar' },
  'config.resume':          { tcg: 'Retomar',                   stealth: 'Retomar' },
  'config.forceNow':        { tcg: 'Atualizar agora',           stealth: 'Atualizar agora' },
  'config.scraping':        { tcg: 'Buscando...',              stealth: 'Buscando...' },
  'config.state':           { tcg: 'Estado',                    stealth: 'Estado' },
  'config.online':          { tcg: 'Online',                    stealth: 'Online' },
  'config.idle':            { tcg: 'Parado',                   stealth: 'Parado' },
  'config.lastScrape':      { tcg: 'Ultima atualizacao',       stealth: 'Ultima atualizacao' },
  'config.lastCards':       { tcg: 'Cartas',                   stealth: 'Registros' },
  'config.lastTotal':       { tcg: 'Total',                   stealth: 'Total' },
  'config.never':           { tcg: 'Nunca',                    stealth: 'Nunca' },
}

export default labels
